{{- if .Values.mcp.enabled -}}
{{- $values := deepCopy .Values.mcp -}}
{{- $ctx := dict "root" . "values" $values "name" "mcp" -}}
{{- include "polytomic.decorateMcpValues" (dict "ctx" $ctx "target" $values) -}}
{{- include "polytomic-base.serviceaccount" $ctx }}
{{- end }}
