# No shared storage.
image:
  tag: "0.0.0-test"

polytomicDeploymentId: "ci-test"

auth:
  url: "https://polytomic.test"

database:
  host: "postgres.example.com"

externalRedis:
  host: "redis.example.com"

operationalBucket:
  provider: s3
  name: ci-operational
  region: us-east-1

sharedVolume:
  mode: emptyDir

secrets:
  existing:
    - name: ci-placeholder-secrets

cronjobs:
  jobs:
    dailySummary:
      enabled: true
